# Generated by Django 3.1.5 on 2021-01-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflow',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
